# Generated by Django 5.2.7 on 2025-10-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('displayable', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
